name: Build QRB ROS packages on Ubuntu

on:
  workflow_call:
    inputs:
      dependencies:
        description: 'List of repositories to checkout, e.g. "owner/repo1 owner/repo2"'
        type: string
        required: false
      colcon_args:
        description: 'Colcon build arguments, e.g. --cmake-args -DCMAKE_BUILD_TYPE=Release'
        type: string
        required: false
      ros-distro:
        description: 'ROS2 distribution to use, e.g. humble'
        type: string
        required: false
        default: jazzy
      apt-packages:
        description: 'List of apt packages to install, e.g. "python3-pip python3-rosdep"'
        type: string
        required: false
      vcstool_repo_yaml: # <-- 新增参数
        description: 'Path to a .repos file to use with vcs import, e.g. repos.yaml. If provided, overrides default checkout/dependencies.'
        type: string
        required: false
        default: ''

env:
    ROS_WS: ${{ github.workspace }}/ros2_ws/
    ROS_SRC: ${{ github.workspace }}/ros2_ws/src

jobs:
  ros-build:
    runs-on: [ubuntu-24.04-arm]
    container: ros:jazzy
    steps:
      - name: Update and install extra packages
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y tree python3-vcstool ${{ inputs.apt-packages }}

      - name: Download code with vcs import
        if: inputs.vcstool_repo_yaml != ''
        run: |
          mkdir -p ${ROS_SRC}
          cd ${ROS_SRC}
          # 下载 .repos 文件
          # 假设 .repos 文件在仓库的根目录，或者你可以调整下载路径
          wget https://raw.githubusercontent.com/qualcomm-qrb-ros/qrb_ros_distro/refs/heads/release-0.2.0/jazzy/repo.yaml -O ${{ inputs.vcstool_repo_yaml }}
          vcs import < ${{ inputs.vcstool_repo_yaml }}

      - name: Checkout source code
        if: inputs.vcstool_repo_yaml == ''
        uses: actions/checkout@v4
        with:
          path: ${{ env.ROS_SRC }}/${{ github.event.repository.name }}
      - name: Checkout dependency
        if: inputs.vcstool_repo_yaml == ''
        run: |
          for repo in ${{ inputs.dependencies }}; do
            git clone https://github.com/${repo}.git ${ROS_SRC}/${repo#*/} || true
          done
      - name: Check ROS dependency
        run: |
          sudo rosdep update
          sudo rosdep install -y --rosdistro ${{ inputs.ros-distro }} --from-paths ${ROS_SRC} --ignore-src
      - name: Build ROS packages
        shell: bash
        run: |
          cd ${ROS_WS}
          source /opt/ros/jazzy/setup.sh
          colcon build ${{ inputs.colcon_args }}
          tree $ROS_WS
          
  ros-build-host:
    runs-on: [ubuntu-24.04-arm]
    steps:
      - name: Base env set up
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y tree ${{ inputs.apt-packages }}
      - name: Add ROS 2 apt repository and install development tools
        run: |
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

          sudo apt update
          sudo apt install ros-dev-tools
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: ${{ env.ROS_SRC }}/${{ github.event.repository.name }}
      - name: Checkout dependency
        run: |
          for repo in ${{ inputs.dependencies }}; do
            git clone https://github.com/${repo}.git ${ROS_SRC}/${repo#*/} || true
          done
      - name: Check ROS dependency
        run: |
          sudo rosdep init
          sudo rosdep update
          sudo rosdep install -y --rosdistro ${{ inputs.ros-distro }} --from-paths ${ROS_SRC} --ignore-src
      - name: Build ROS packages
        shell: bash
        run: |
          cd ${ROS_WS}
          source /opt/ros/jazzy/setup.sh
          colcon build ${{ inputs.colcon_args }}
          tree $ROS_WS
